apiVersion: v1
kind: Service
metadata:
  labels:
    name: todo
  name: todo
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: todo
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  selector:
    matchLabels:
      app: todo
  replicas: 1
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: harbor.tanzuworld.com/openso/todo:latest
        ports:
        - containerPort: 5000
